name: Production Readiness Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  production-tests:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build application
      run: npm run build
    
    - name: Start preview server
      run: npm run preview &
      
    - name: Wait for server
      run: sleep 5
    
    - name: Run production tests
      run: npm run test:production
    
    - name: Stop preview server
      run: pkill -f "vite preview" || true
